In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
two_d = [[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]

In [12]:
import sys
sys.getsizeof(two_d)

80

In [13]:
points = torch.tensor(two_d)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
sys.getsizeof(points), points.element_size() * points.numel()

(72, 24)

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
points[0, 1]

tensor(1.)

In [19]:
points[0]

tensor([4., 1.])

## 3.3 Indexing tensors

In [20]:
# Adds a dimension of size 1. This is a common way to add a batch dimension to a tensor.
# If points is a 1D tensor, points[None] returns a 2D tensor with a single row.
# If points is a 2D tensor, points[None] returns a 3D tensor with a single row of columns.
# If points is a 3D tensor, points[None] returns a 4D tensor with a single row of matrices.
# This behavior is a shorthand for unsqueeze.
points[None] 

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## 3.5 Tensor element types

In [21]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [22]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [23]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [24]:
# The final operation will preserve the data type of the largest data type (in this case, double).
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards


tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 3.7 Tensors: scenic views of Storage

In [25]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/tmp/ipykernel_431006/2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()
/home/jmendoza/dl/venv/lib/python3.10/site-packages/IPython/lib/pretty.py:779: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/home/jmendoza/dl/venv/lib/python3.10/site-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To ac

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [26]:
points.untyped_storage()

 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]

In [27]:
points.untyped_storage()[2]

128

In [28]:
points_storage = points.storage()
points_storage[0]

/tmp/ipykernel_431006/322848230.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()
/tmp/ipykernel_431006/322848230.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage[0]


4.0

In [29]:
points.storage()[1]

/tmp/ipykernel_431006/417633554.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()[1]


1.0

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

/tmp/ipykernel_431006/2616098612.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()
/tmp/ipykernel_431006/2616098612.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage[0] = 2.0


tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [32]:
second_point.size()

torch.Size([2])

In [33]:
second_point.shape

torch.Size([2])

In [34]:
points.stride()

(2, 1)

In [35]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [36]:
second_point.storage_offset()

2

In [37]:
second_point.stride()

(1,)

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [39]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [40]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [41]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
id(points.storage()) == id(points_t.storage())

/tmp/ipykernel_431006/2282178668.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(points.storage()) == id(points_t.storage())


False

In [43]:
points.stride()

(2, 1)

In [44]:
points_t.stride()

(1, 2)

In [45]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [46]:
transpose_t.shape

torch.Size([5, 4, 3])

In [47]:
some_t.stride()

(20, 5, 1)

In [48]:
transpose_t.stride()

(1, 5, 20)

In [49]:
points.is_contiguous()

True

In [50]:
points_t.is_contiguous()

False

In [51]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [52]:
points_t.storage()

/tmp/ipykernel_431006/3158410579.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_t.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [53]:
points_t.stride()

(1, 2)

In [54]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [55]:
points_t_cont.stride()

(3, 1)

In [56]:
points_t_cont.storage()

/tmp/ipykernel_431006/1562932398.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_t_cont.storage()


 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [57]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [58]:
short_points.dtype

torch.int16

In [59]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [60]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [61]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [62]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

## 3.9 Moving tensors to the GPU

In [67]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [68]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [69]:
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [70]:
points_gpu = points.to(device='cuda')

In [71]:
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [72]:
points_gpu = points.to(device='cuda:0')

In [73]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [74]:
points_gpu = points_gpu + 4

In [75]:
points_gpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]], device='cuda:0')

In [76]:
points_cpu = points_gpu.to(device='cpu')

In [77]:
points_cpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]])

In [78]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [79]:
points_cpu, points_gpu

(tensor([[ 8.,  2.],
         [10.,  6.],
         [ 4.,  2.]]),
 tensor([[ 8.,  2.],
         [10.,  6.],
         [ 4.,  2.]], device='cuda:0'))

## 3.10 NumPy interoperability

In [80]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [82]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## 3.12 Serializing tensors

In [83]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [85]:
# Using a file descriptor
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [86]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [87]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [88]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [89]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [90]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [91]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [92]:
dset

<Closed HDF5 dataset>